name: CI
on:
  merge_group:
  push:
    branches:
    - main
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches:
    - "**"
    paths-ignore:
    - '**/*.md'
jobs:
  lint:
    name: Linting with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.23.x]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        cache: false # golangci-lint-action has its own cache
        go-version: ${{ matrix.go-version }}
    - name: Staticcheck
      shell: bash
      env:
        BUILDTAGS: "functional"
        VERSION: "v0.6.0"
      run: |
        go install "honnef.co/go/tools/cmd/staticcheck@${VERSION}"
        echo "::add-matcher::./.github/actions/staticcheck-matchers.json"
        $(go env GOPATH)/bin/staticcheck -tags "${BUILDTAGS}" ./...
    - name: golangci-lint
      env:
        GOFLAGS: -tags=functional
      uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
      with:
        version: v1.64.5
  test:
    name: Unit Testing with Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.23.x]
    env:
      DEBUG: true
      GOFLAGS: -trimpath
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test (Unit)
      run: make test
